[package]
name = "async-write-bincode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
