[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bevy_app = "0.15.1"
bevy_ecs = "0.15.1"
bevy_time = "0.15.1"
bincode = "1.3.3"
serde = { version = "1.0.217", features = ["derive"] }
slab = "0.4.9"
tokio = { version = "1.43.0", features = ["sync"] }
