[package]
name = "algo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
itertools = "0.14.0"
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
