[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
env_logger = "0.11.6"
log = "0.4.25"
protocol = { path = "../protocol" }
tokio = { workspace = true }
