# https://github.com/bevyengine/bevy/issues/1110
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=off"]

[alias]
dev-client-local = "r -p client -- --server-ip 127.0.0.1"
dev-server = "r -p server"